export const languages = {
  Python: "python",
  JavaScript: "javascript",
  Java: "java",
  HTML: "html",
  CSS: "css",
  SQL: "sql",
  Bash: "bash",
  PowerShell: "powershell",
  R: "r",
  MATLAB: "matlab",
  Perl: "perl",
  Ruby: "ruby",
  PHP: "php",
  Go: "go",
  Scala: "scala",
  Kotlin: "kotlin",
  Rust: "rust",
  TypeScript: "typescript",
  C: "c",
  "C#": "csharp",
  "C++": "c_cpp",
  Dart: "dart",
  Swift: "swift",
  Elixir: "elixir",
  Clojure: "clojure",
  Haskell: "haskell",
  Lua: "lua",
  "F#": "fsharp",
  Groovy: "groovy",
  Racket: "racket",
  OCaml: "ocaml",
  Julia: "julia",
  "Visual Basic": "vb",
  Pascal: "pascal",
};